//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AalborgZooProjekt.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingList()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
        public int ShopperId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Shopper Shopper { get; set; }
    }
}
