//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AalborgZooProjekt.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordChanged
    {
        public int Id { get; set; }
        public string DateChanged { get; set; }
        public Nullable<int> ShopperId { get; set; }
    
        public virtual Shopper Shopper { get; set; }
    }
}
